### ISSUE TITLE
Request: filebot

### ISSUE THREAD

**Issue by StephenBrown2** [rockstor/rockon-registry#109]
rednoah has created a node server app for filebot and packaged it in a docker container here: https://hub.docker.com/r/rednoah/filebot/

The filebot Node Service is here: https://github.com/filebot/filebot-node

and the How to is here: https://www.filebot.net/forums/viewtopic.php?f=13&t=2733 (It's pretty basic)

But I figured it would be a good addition to a media server.

**Comment by StephenBrown2** [comment]
So far I've got this json:
https://gist.github.com/StephenBrown2/d14ef544562a75600c788d2ded638ffe

I'll submit it as a PR soon, but if anyone has any suggestions, I'll gladly take them.

**Comment by magicalyak** [comment]
If you tested it go and submit the PR.

**Comment by phillxnet** [comment]
@StephenBrown2 Thanks for the proposal and leg work. I'm just working through our old issues.
Do please consider submitting your Rock-on as @magicalyak suggested. It's often easier for people to chip in with suggestions in the context of an open pull request.

Otherwise if no one want to take this on I think it's best we close this issue.

Labelling hopefully appropriately.

**Comment by tyukh** [comment]
Such a Rock-on is in my short list. I hope ETA within month.

**Comment by magicalyak** [comment]
Was hoping @StephenBrown2 would submit it but if he's not just submit it, it's easier to modify in the PR. Happy to help and make suggestions once you do.  Definitely link it back to this issue (just paste the link to this issue in a comment on the PR).

**Comment by StephenBrown2** [comment]
Sorry for the long silence, I haven't been running my RockStor server for a while now, but it doesn't look like much has changed, so I submitted my gist as #215 for review and merge.
