### ISSUE TITLE
Rockon PRs - are they being managed?

### ISSUE THREAD

**Issue by bennysp** [rockstor/rockon-registry#147]
Hi - I have submitted the below PR for adding Nextcloud Rockon.  Looking at the list and date of all the PRs, I am questioning if this is actively reviewed.

Is there anything I can do to help with my PR?  Anything I can do to contribute PR reviews to this community?

I love Rockstor and I think these Rockons help expand the functionality.

https://github.com/rockstor/rockon-registry/pull/145

**Comment by phillxnet** [comment]
@bennysp Thanks for chasing this issue up. The rockon-registry repo is definitely due for a little more attention. I was chuffed myself to see you pr but I am not the best candidate to review the indicated pr as my docker knowledge is wanting (but improving) and in this specific case I am also unfamiliar with Nextcloud.

We could see if @magicalyak, @MFlyer, @daniel-illi, or @florianduclot have time for a review / double check as they are all more up on such things than myself and have successfully reviewed a number of other rock-ons between them. I've made a note on the issue to this end and have linked back to your forum post where I have also requested reviewers.

And thanks for you offer to help re the review process. You could look to the pending pr's and see if there are any others that are similarly awaiting review and if you are able you could test and review them. This should then help with the number of rock-on pr's that project lead @schakrava can then merge when he next does a rockon-registry stint. 

Thanks for your patience and lets hope we get some 'bites' on this one.

Glad your enjoying Rockstor and yes the Rock-ons and specifically their pr merging has rather been neglected. Hopefully things should pickup as we get the exiting 'behind the scenes' plans/backlog into action.

**Comment by magicalyak** [comment]
I'll go through them in the next few days, sorry about the delays, rough last few months for me and I haven't been watching closely.  I'll run through them soon.

**Comment by bennysp** [comment]
Thanks @magicalyak !

**Comment by magicalyak** [comment]
I need to go through them, thanks for being patient, will try to cover all of them in the next two weeks.

**Comment by phillxnet** [comment]
@bennysp Re this issues title: "Rockon PRs - are they being managed?"

I have now addressed every pr and issue in this repository, with the much appreciated assistance of all other participants. Thanks mainly to @magicalyak and @FroggyFlox reviews and suggestions, along with a few less regular reviewers who were all credited in each case.

And by way of my recently extended capabilities within these repositories and Rockstor, I have merged  all that appeared to be ready. All others have a question / comment / label awaiting others attention prior to their being merged.

Yesterday we had 18 pull requests closed, with only 2 un-merged for reasons explained in their comments. The result is an additional 7 rock-ons in the repo (although 2 were prior merged but did not show up due to no root.json entry), the remainder were bug fixes, improvements, updates.

We are now awaiting deployment of the repository content where upon I would like to close this issue.

Thanks for the prompt, as usual these things are mostly down to available resources and the shortage of reviewers with the often specialist knowledge required.

I have also authored a wiki entry in the Rockstor forum to assist those willing to review pending pull requests with a view to maintaining a less unreasonable/discouraging backlog:

"How to test a Rock-on pull request"
https://forum.rockstor.com/t/how-to-test-a-rock-on-pull-request/5224

Hopefully we can see your much sought after nextcloud rock-on work come to a conclusion.
Linking for context:
"Nextcloud addition" #145

Again I can only apologies for the delays and hope to make a difference going forward.
