### ISSUE TITLE
add seafile Rock-on

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockon-registry#182]
Forum member noorbertt has requested the addition of a Seafile Rock-on. Creating this issue to note this request. Please update the following forum thread with this issues resolution:

https://forum.rockstor.com/t/update-the-docker-list/5898

A quick search would suggest that Seafile has for some time been available in a docker image:
https://forum.seafile.com/t/new-seafile-docker-is-ready/5856
(Apr 2018)
which in turn links to the following GitHub repo:
https://github.com/haiwen/seafile-docker
which looks to be active but it is not currently clear which dockerhub image is the official one, or if an official docker hub image even exists.

**Comment by phillxnet** [comment]
From: https://manual.seafile.com/deploy/deploy_with_docker.html
It would appear that the DockerHub image is seafileltd/seafile ie:

https://hub.docker.com/r/seafileltd/seafile

**Comment by FroggyFlox** [comment]
That is indeed an important rock-on to have... There has been an attempt by @TexasDex forum user who graciously shared his json file, but this container was showing some rather odd behavior that was unfortunately blocking:
https://forum.rockstor.com/t/trying-to-make-a-new-rock-on-for-seafile/5238

I haven't had the time to troubleshoot this further since, but it might be worth the effort.

**Comment by TexasDex** [comment]
The issue was that rockstor by default mounts /etc/localtime into the container.  For some reason, that causes seahub (the web GUI component of Seafile) to crash and restart infinitely.

https://github.com/haiwen/seafile-docker/issues/101

**Comment by TexasDex** [comment]
I think I figured something out: The container skips the part where it overwrites /etc/localtime if TIME_ZONE is set.  So I added that to the Seafile.json file and it seems to work (although I'm not sure if my env is representative, since I'm also spinning the docker container up via CLI sometimes).  Could someone else give it a try?  Newest JSON here: https://forum.rockstor.com/t/trying-to-make-a-new-rock-on-for-seafile/5238/16

**Comment by FroggyFlox** [comment]
Hi @TexasDex ,

Thanks again for pinpointing where the problem originated.
Unfortunately, your updated JSON still doesn't work for me, but this time the origin lies with the container's image. Indeed, although the little bit of bash script used by the image in `create_links.sh` works as intended, it doesn't work with the base image that they have chosen as it does not contain the required `/usr/share/zoneinfo`. As a result, even with specifying the `TIME_ZONE` environment variable at docker run time, the containers fails to create with the following error:
```
Apr 10 13:47:53 rockdev dockerd[4675]: invalid time zone
```

There is a nice description and workaround in the following Github issue (linked below), but I unfortunately do not see how this would help us in the meantime... It seems to me it is something that needs to be resolved by the seafile docker image itself (as you already pointed in their related Github issue). At first look, it seems to me that the `create_links.sh` script used in this image always fails even without the timezone set, it simply fails silently. Timezone management is not my forte at all, however, so I may be wrong.
https://github.com/phusion/baseimage-docker/issues/415

**Comment by phillxnet** [comment]
Closing as Fixed by @TexasDex in pr #184 

Thanks to @TexasDex and to @FroggyFlox for review (see also @FroggyFlox's pr comments/contributions)
