### ISSUE TITLE
Deluge json has no incoming port defined

### ISSUE THREAD

**Issue by Arderos** [rockstor/rockon-registry#205]
Right now only the WebUI (8112) and daemon (58846) ports are configured in json but torrent client needs a port for incoming connections and right now no such port is defined which makes seeding very slow if not non-functional.

**Comment by phillxnet** [comment]
@Arderos Thanks for your report.

We have a related issue opened by @Psykar where they propose giving this Rock-on --net=host which is something I like to avoid. Do you fancy preparing a pull request for this issue where a set number of 'incoming' connection ports are defined? If that can be made workable. If you do have a go at this then please reference both this issue and @Psykar's as then we can then tie them all together. If we can't avoid --net=host then we should give some kind of user warning related to this.

If you have a go at this issue via a pull request then please indicate here so that we can avoid duplication of effort.

Thanks.

**Comment by phillxnet** [comment]
Linking for context to @Psykar's open pull request:
"Change deluge to --net=host to allow remote connec" #193

**Comment by Arderos** [comment]
We can define incoming port in json, no problem, but the user will have to input the same port in Deluge's config. AFAIK, there are no ENV to define it - has to be done manually.
So the question is - do we go "double config" route whilst avoiding "--net=host" or go with "--net=host"?

**Comment by phillxnet** [comment]
> So the question is - do we go "double config" route whilst avoiding "--net=host" or go with "--net=host"?

Exactly.

But maybe better to have this double config, even though it's not in keeping with the Rock-on config 'easy' ethos (except in particular examples where it is unavoidable) than to pull the rock-on entirely though. I don't think this app is worth the exception and it's consequent risks. We are also preparing to do a tidy soon where all non fully functional Rock-ons are likely to be pulled.

One way this could go, if it's seen to be worth the effort, would be to have a supporting doc entry. This was recently done by @FroggyFlox in the following pull requests:
"Add YouTrack Official rock-on" #202
Although that example was a little more extreme as it concerned pre-install config, but still.

So maybe we need a rockstor-doc pull request to add a "Rock-ons with write-ups" section for Deluge? And link to that from within the description of the Deluge Rock-on.

> ... will have to use one port and one port only ...

Does Deluge only have to option to set a single port for this then? The Rock-on could have multiple ports set, but of course more ports makes for more UX complexity. We don't yet have a range capability but that might be just the job, if we had it, in this case.

**Comment by phillxnet** [comment]
Linking to "Rock-ons with write-ups":
http://rockstor.com/docs/docker-based-rock-ons/overview.html#rock-ons-with-write-ups

**Comment by Arderos** [comment]
> But maybe better to have this double config, even though it's not in keeping with the Rock-on config 'easy' ethos (except in particular examples where it is unavoidable) than to pull the rock-on entirely though.
Yeah, I couldn't agree more. "--net=host" seems like a huge overkill for a torrent client and the issue stems from the original container from linuxserver.io which is supposed to be run with host networking by design.
I will try to do a custom json and describe an additional port. If all goes well, I'll create a PR with that json.


> Does Deluge only have the option to set a single port for this then? The Rock-on could have multiple ports set, but of course more ports makes for more UX complexity. We don't yet have a range capability but that might be just the job, if we had it, in this case.

It sure does. You either define a single port or select "Use Random Port".

**Comment by Psykar** [comment]
Unfortunately making the port external on docker wasn't all that was required - UPNP wasn't working either.
So unless you use `--net=host` you actually have three places you need to set configs
* rockstor
* deluge
* your router

I ended up running Deluge outside of Rockstor. If you find a way to get upnp to work as well without using `--net=host` I'd love to hear it!

**Comment by phillxnet** [comment]
@Psykar Thanks for you input on this one. We're nudging it along, bit by bit.

I'm still in favour of having a doc entry for these config steps as not all folks have UPnP enabled on their routers anyway (domestic routers tend to have it enabled though) and so that element is really outside of Rockstor's remit and in the realm of external network config / remote access setup. Better we doc this setup and maintain a safer implementation of Deluge than drop it I think.

**Comment by phillxnet** [comment]
@Arderos and @Psykar It's looking very much like we can't get his one sorted within our current Rock-on ideal of not using --net=host except when absolutely necessary. It seems the consensus here is that it's too much just to allow Deluge.
The image is still current i.e. 15 days ago as last updated:
https://hub.docker.com/search?q=linuxserver%2Fdeluge&type=image

Closing as an unfortunate limitation of our trying to avoid more and more uses of host networking.
