### ISSUE TITLE
Docker port values treated as int type instead of string

### ISSUE THREAD

**Issue by tyukh** [rockstor/rockon-registry#214]
Some docker images uses port values specified with protocol type i.e. something like that `-p 51413:51413/udp` (https://docs.linuxserver.io/images/docker-transmission) so it produce following error
```
Errors occurred while processing updates for the following Rock-ons (Transmission: invalid literal for int() with base 10: '51413/udp').

            Traceback (most recent call last):
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 111, in post
    self._create_update_meta(r, rockons[r])
  File "/opt/rockstor/eggs/Django-1.8.16-py2.7.egg/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rockstor/src/rockstor/storageadmin/views/rockon.py", line 215, in _create_update_meta
    if (len(set(map(int, ports.keys())) ^ set(cur_ports)) != 0):
ValueError: invalid literal for int() with base 10: '51413/udp'
```
json:
```
          "51413/udp": {
            "description": "Torrent Port UDP. Default: 51413.",
            "host_default": 51413,
            "label": "Torrent port UDP",
            "protocol": "udp"
          }
```

**Comment by FroggyFlox** [comment]
Hi again, @tyukh , and thanks for bringing this up,
I'm currently on my phone so please excuse my brevity.

Have you tried using the optional "protocol" key for that? See below for description:
https://github.com/rockstor/rockon-registry/blob/master/README.md#port-object

**Comment by tyukh** [comment]
> Hi again, @tyukh , and thanks for bringing this up,
> I'm currently on my phone so please excuse my brevity.
> 
> Have you tried using the optional "protocol" key for that? See below for description:
> https://github.com/rockstor/rockon-registry/blob/master/README.md#port-object

My fault. Thanks a lot!  I used these options, but I did not correctly understand what they give as a result. It is probably worth adding an example of use in the form of example json-fragment and the resulting string.

**Comment by tyukh** [comment]
The error went away when using the protocol key, but the result is not the same as I expected. The situation is as follows: it is necessary to map the settings of the container 
```
  -p 51413:51413 
  -p 51413:51413/udp
```
to the json file. I assumed that this is how 
```
          "51413": {
            "description": "Torrent Port TCP. Default: 51413.",
            "host_default": 51413,
            "label": "Torrent port TCP"
          },
          "51413": {
            "description": "Torrent Port UDP. Default: 51413.",
            "host_default": 51413,
            "label": "Torrent port UDP",
            "protocol": "udp"
          }
```
would work, but in the interface it gives only one "Torrent port UDP" field. It turns out that first 51413 (Torrent port TCP) is ignored, and specifying the protocol for second 51413 does not lead to the value "51413/udp", at least for display in the interface.

And one more thing: the default port values increased compared to those specified in json file: instead of 51413 it became 51414, instead of 9091 it became 9094. As I understand it, it’s planned, but this behavior is somewhat unpredictable in the first place, and secondly, auto-increment is logical if the port is busy , and not just declared in other plugins.

**Comment by FroggyFlox** [comment]
> It turns out that first 51413 (Torrent port TCP) is ignored, and specifying the protocol for second 51413 does not lead to the value "51413/udp", at least for display in the interface.

That is indeed the expected behavior when the same port is defined twice as one overwrites the other. We actually shouldn't let that go in the JSON and should make sure we throw an error when that case is found in a JSON (in my opinion).

Now, onto what you need:
```
  -p 51413:51413 
  -p 51413:51413/udp
```
As docker maps by default to TCP when undefined (see [Docker doc](https://docs.docker.com/config/containers/container-networking/)), I assume you need that port 51413 mapped to both UDP and TCP. In this case, you simply need to omit the "protocol" key as then Rockstor will map it to both UDP and TCP (this is Rockstor's default).
In this case, I would thus leave your JSON as:
```json
          "51413": {
            "description": "Torrent Port. Default: 51413.",
            "host_default": 51413,
            "label": "Torrent"
          }
```
This is where this part is taken care of:
```python
def port_ops(container):
    ops_list = []
    for po in DPort.objects.filter(container=container):
        pstr = '%s:%s' % (po.hostp, po.containerp)
        if (po.protocol is not None):
            pstr = '%s/%s' % (pstr, po.protocol)
            ops_list.extend(['-p', pstr])
        else:
            tcp = '%s/tcp' % pstr
            udp = '%s/udp' % pstr
            ops_list.extend(['-p', tcp, '-p', udp, ])
    return ops_list
```
https://github.com/rockstor/rockstor-core/blob/c3a5c7448780d7fe2643233b4fae1c445f24c5db/src/rockstor/storageadmin/views/rockon_helpers.py#L170-L181

**Comment by FroggyFlox** [comment]
Sorry for the double post; I just realized I forgot to answer your other questions:

> the default port values increased compared to those specified in json file: instead of 51413 it became 51414, instead of 9091 it became 9094. As I understand it, it’s planned, but this behavior is somewhat unpredictable in the first place, and secondly, auto-increment is logical if the port is busy , and not just declared in other plugins.


You are correct that this is the expected behavior as well as we then make sure to avoid conflicts with another used port on the machine. This is taken care by:
https://github.com/rockstor/rockstor-core/blob/c3a5c7448780d7fe2643233b4fae1c445f24c5db/src/rockstor/storageadmin/views/rockon.py#L130-L136
```python
    @staticmethod
    def _next_available_default_hostp(port):
        while (True):
            if (DPort.objects.filter(hostp=port).exists()):
                port += 1
            else:
                return port
```

I agree with you that it can be seen as unpredictable from a user perspective as the user doesn't know what ports all the other rock-ons have in their definition. On the other hand, the reason this is done is so that the user doesn't have to worry about these things and Rockstor takes care of selecting another port that is currently not in use with another rock-on for the user.


> auto-increment is logical if the port is busy , and not just declared in other plugins. 

That is a good point. I'm not sure how we can detect that (not familiar with that), but we could change the way we do this, indeed. We would need to substantially revise how we do this though, and also think about how stable such setting will be if one is installed but not running and how another rock-on installation would be able to detect that.
Please do share ideas on how to do so, however, as I don't really know what would be the best way to detect that (using docker tools might be a way), and I may be overthinking that one as well.
In case you're interested and haven't seen it yet, we do have some developer's notes on how the rock-ons framework is organized in our forum:
https://forum.rockstor.com/t/rock-on-framework-implementation/6288

I hope I was able to answer your questions, or at least bring some elements of answer.

Cheers,

**Comment by tyukh** [comment]
> As docker maps by default to TCP when undefined (see [Docker doc](https://docs.docker.com/config/containers/container-networking/)), I assume you need that port 51413 mapped to both UDP and TCP. In this case, you simply need to omit the "protocol" key as then Rockstor will map it to both UDP and TCP (this is Rockstor's default).

Thank you, now everything is clear. Although it seems to me that the best solution for greater predictability would be to reflect the docker approach: the protocol is not specified - TCP, the port number is not unique - the combination of port / protocol (composite key) is unique.

> You are correct that this is the expected behavior as well as we then make sure to avoid conflicts with another used port on the machine. This is taken care by:
> https://github.com/rockstor/rockstor-core/blob/c3a5c7448780d7fe2643233b4fae1c445f24c5db/src/rockstor/storageadmin/views/rockon.py#L130-L136

In my opinion, this function should look something like this
```
def _next_available_default_hostp(port):
 for ro in RockOn.objects.all(state='installed'):
  for co in DContainer.objects.filter(rockon=ro):
   for po in DPort.objects.filter(container=co):
    if (po.hostp == port):
     port += 1
 return port
```
> Please do share ideas on how to do so, however, as I don't really know what would be the best way to detect that (using docker tools might be a way), and I may be overthinking that one as well.

Below is an example (not mine) of checking ports from another project
```
try_to_bind_port() {
  local port="${1}"
  local protocol="${2}" # tcp or udp
  # Try to create docker container that bounds given port.
  docker run --rm -p "${port}:${port}/${protocol}" --entrypoint /bin/echo "${DOCKER_IMAGE}:${DOCKER_TAG}" "Port ${port}/${protocol} is free." 2>/dev/null
}

check_free_ports() {
  echo "Checking available ports"
  while ! try_to_bind_port "${HTTP_PORT}" "tcp"; do
    test "${UNATTENDED}" = "false" || fail "Port ${HTTP_PORT} is in use."
    read -r -p "Port ${HTTP_PORT} is already in use, please choose a different HTTP port for UNMS. [${ALTERNATIVE_HTTP_PORT}]: " HTTP_PORT
    HTTP_PORT=${HTTP_PORT:-$ALTERNATIVE_HTTP_PORT}
  done

  ///......
}
```
Am I closing the issue?

**Comment by tyukh** [comment]
> You are correct that this is the expected behavior as well as we then make sure to avoid conflicts with another used port on the machine.

Another issue: if the rock-on was installed and then removed, then when reinstalling, the port values are substituted from the database and the ports are not checked for occupancy, although during this time the ports might already be occupied.
