### ISSUE TITLE
Postgres v10.6 is actually v12

### ISSUE THREAD

**Issue by holmesb** [rockstor/rockon-registry#223]
I won't profess to be a rockon expert, but somehow the [tag ](https://github.com/rockstor/rockon-registry/blob/37fd972d7828decac95edde973118e259124b06c/postgres-10.6.json#L12)isn't causing this version to be pulled.

A `docker inspect <container>` gives:
```
...
"Env": [
  "PG_MAJOR=12",
  "PG_VERSION=12.2-2.pgdg100+1",
...
```

I'm using rockstor 3.9.2-48

**Comment by FroggyFlox** [comment]
Hi @holmesb,

I believe the answer lies in your Rockstor version:


> I'm using rockstor 3.9.2-48

Indeed, we have had several improvements directly related to using different tags for the same docker image since 3.9.2-48. In particular:
- Rockstor 3.9.2-49: https://github.com/rockstor/rockstor-core/releases/tag/3.9.2-49
  this one includes the following PR of interest: https://github.com/rockstor/rockstor-core/pull/2016
- Rockstor 3.9.2-51: https://github.com/rockstor/rockstor-core/releases/tag/3.9.2-51
  this one includes the following PR of interest: https://github.com/rockstor/rockstor-core/pull/2069

My recommendation would thus to first uninstall your postgresql rock-on, refresh your list of rock-ons by clicking the "Update" button on the Rock-ons page, then update your Rockstor install to the latest version (now 3.9.2-56), and then refresh again your list of rock-ons, and then installing the postgres rock-on should pull the correct version.

Hope this helps,

**Comment by holmesb** [comment]
Hi @FroggyFlox I suspsected as much.   After I switched from stable to testing, it's unclear how I can force the update to start.  Must I wait for the next scheduled update event to occur?  Version has changed down to 3.9.2-1.

I also can't access the rockon page now `Unknown internal error doing a GET to /api/rockons?page=1&format=json&page_size=5000&count=`  but perhaps that will fix itself after I figure how to update.

**Comment by phillxnet** [comment]
> After I switched from stable to testing,

Hello again @holmesb, I see you have posted this up/down grade issue in the forum. I'll link to that and pick it up there.

https://forum.rockstor.com/t/cant-activate-stable-local-variable-appliance-referenced-before-assignment/6933

**Comment by holmesb** [comment]
Upgrading rockstor to latest version per @FroggyFlox's suggestion has fixed.  Thanks also to @phillxnet helping me upgrade.
