### ISSUE TITLE
Remove deprecated image: Koel

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockon-registry#254]
Our rock-on for the lightweight music streamer Koel is unfortunately not present in docker hub anymore:
```
rockdev-Leap15-2:~ # docker pull binhex/arch-koel
Using default tag: latest
Error response from daemon: pull access denied for binhex/arch-koel, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

We thus need to deprecate it.

**Comment by FroggyFlox** [comment]
For alternative, there seems to be another image, recently updated, with 100K+ pulls, but that one would need some database linking that should be facilitated by https://github.com/rockstor/rockstor-core/pull/2207:
https://hub.docker.com/r/hyzual/koel

This could be interesting to keep in mind once/if this linked PR is merged.

**Comment by phillxnet** [comment]
@FroggyFlox I'm addressing the removal of this Rock-on via #281 but you noted a reference to a core pr of yours that is now merged and a new image https://hub.docker.com/r/hyzual/koel.
I'll continue to remove the existing one and if need be we can open a new issue to address adding in a replacement to the indicated alternative image as it was updated only 9 days ago so that looks to be promising.
