### ISSUE TITLE
Remove deprecated image: Plexpy

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockon-registry#255]
The linuxserver/plexpy image is now deprecated; the docker hub page reads:

> DEPRECATED PLEASE USE https://hub.docker.com/r/linuxserver/tautulli (USING EXISTING DATA IS FINE)

It thus recommends to use the Tautulli project instead, which seems to be able to be a drop-in replacement.

**Comment by FroggyFlox** [comment]
We should try to resolve #256 first before addressing this issue.

**Comment by FroggyFlox** [comment]
Now that #259 has been merged (thanks to @Hooverdan96!), this issue can be addressed.

**Comment by Hooverdan96** [comment]
@FroggyFlox, @phillxnet,
since we have multiple Rockons to deprecate, would it be better for you to do them all at once (for the next Rockon release), since it involves removing entries from the central root.json file that is involved with any new Rockon pull request? That way you don't have to reconcile all of them as you merge the various new/changed ones?
And/or should we combine multiple deprecations into one pull request to minimize the reconciliation required? I know, that kind of goes against the one issue, one pull request, but am wondering since it affects a single file...
