### ISSUE TITLE
[New rock-on] Tautulli

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockon-registry#256]
As described in #255 , we should create a new rock-on for the Plexpy replacement: Tautulli:

main website: https://tautulli.com/
docker hub: https://hub.docker.com/r/linuxserver/tautulli

@phillxnet , as all Linuxserver.io images, it supports multiple architectures and is regularly maintained/updated.

**Comment by Hooverdan96** [comment]
@FroggyFlox I will take a look at setting one up.

**Comment by Hooverdan96** [comment]
@FroggyFlox - I actually found the official container: https://hub.docker.com/r/tautulli/tautulli
It supports multiple architectures
The one thing I see is that in order to update that container it requires a stop/remove container/pull/restart process, which I believe Rockstor doesn't support at this time (unless watchtower is utilized). The Linuxserver server image for tautulli also requires watchtower for updates (it seems only Plex is automatically updated every time the container is restarted) or a manually removal of the image and reinstallation...
I've been testing with the linuxserver image which works well so far (on amd64), but I think you want to use the official where possible.
So, unless you have objections/concerns I will switch to the official image and test with that.
One question remains, do I need to/should I expose the timezone environment variable or are you already covering that in the docker command you construct?

**Comment by phillxnet** [comment]
@Hooverdan96 Re:
> ... or are you already covering that in the docker command you construct?
I'm pretty sure we already cover this and have just found a forum post by @FroggyFlox on the same:
https://forum.rockstor.com/t/plex-from-official-image/5676/3
containing the following GitHub references.

https://github.com/rockstor/rockstor-core/blob/33917f112011d13e702633f525f2afdc0de78238/src/rockstor/storageadmin/views/rockon_helpers.py#L186-L187

@FroggyFlox may correct me on this however.

**Comment by Hooverdan96** [comment]
Ah yes, I now remember coming across a forum thread a while ago on this in the context of the official Plex Rock-on. And, yes, the official Tautulli image works just fine without explicitly calling out the TZ variable. I now tested with the official image, and all seems to be fine. I will create a pull request for this.
