### ISSUE TITLE
Vaultwarden alpine is not available for arm64

### ISSUE THREAD

**Issue by RlndVt** [rockstor/rockon-registry#298]
Vaultwarden alpine is not available for arm64, for best compatibility use the 'normal' latest tag.

Alternatively offer a Vaultwarden and a Vaultwarden-alpine Rockon solution.

**Comment by phillxnet** [comment]
@RlndVt Thanks again for reporting a nice catch. We definitely favour also having arm64 compatibility where ever possible.
See: https://github.com/rockstor/rockstor-core/issues/2191
"[arm64] Discourage or prevent installation of Rockons that are not available on the machines architecture"

@FroggyFlox When/if you get time. Your input would be appreciated on this one - as always. No worries otherwise I'll hopefully get around to have a look shortly.

> Alternatively offer a Vaultwarden and a Vaultwarden-alpine Rockon solution.

I know we've done this from time to time but it's certainly not the most elegant solution. I'd prefer to back a single option in this case. If at all possible.

**Comment by Hooverdan96** [comment]
If I look at the changes (#297) tied to issue #296 
the renamed Bitwarden to Vaultwarden is referencing the docker image from here:
https://hub.docker.com/r/vaultwarden/server

This image actually supports all architectures we desire:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/35113775/143938350-36a110ec-4978-4b7c-a62b-796f457a0aac.png">
So, I think, once the description in #297 is updated to include the available architecture language, then this could likely be closed.

**Comment by RlndVt** [comment]
#297 still reverences the 'alpine' tag, not 'latest', as that was the tag previously. Changing the tag to latest would indeed be a fix.

![IMG_20211130_072203](https://user-images.githubusercontent.com/1658570/143952056-f5c6281e-a044-466f-9cd9-552f6325db67.jpg)

**Comment by Hooverdan96** [comment]
@RlndVt nice catch, that I didn't even look at :).
