### ISSUE TITLE
make folder into the Docker folder ?

### ISSUE THREAD

**Issue by mattthhdp** [rockstor/rockon-registry#304]
![2022-01-24_10-45-59](https://user-images.githubusercontent.com/10604324/150815674-5568bea6-43bb-47bc-bd4e-47bc6cfc0c1b.png)

i would be more convenient to have a folder structure like this
![2022-01-24_10-47-54](https://user-images.githubusercontent.com/10604324/150815941-072d791e-b28e-43c5-a968-6ea30a420216.png)

**Comment by phillxnet** [comment]
@mattthhdp It's actually recommended in our docs and in the tooltip (?) of each Rock-on install wizard at the point where you select a config and/or data share to use a unique one for each Rock-on.
Take a look at the docs here:

https://rockstor.com/docs/interface/overview.html

So in short you use one Rock-ons-root share for all the docker images which are etheirial anyway. Then you create a specific share for each and every share required by each Rock-on. These can be anyway but are then each not only a directory in their own right but nigh-on a filesystem also as each share in Rockstor is also a btrfs sub-vol.

Let me know if I've miss read your comment/suggestion here. I.e. were you actually talking about the rock-ons-root, as that is the only shared subvol (share in Rockstor speak) that is common to all Rock-ons when following our guidelines. Of course you can use the same share for multiple Rock-ons but it has the potential to clash if two or more rock-ons share a config file for example. That's why we recommened in the Web-UI and docs that a unique share be used for each Rock-ons. In many of the Rock-on install wizard mouse over hints we also suggest a share name to make this clearer. I.e. Plex-config Plex-data or the like. It makes for seperation of concerns and greater robustness.

Incidentally it would be better to raise such things on our forum first actually:
https://forum.rockstor.com/
More eyes there as only the developers tend to look on GitHub. That way we can formulate on the forum what the exact issue is, if any, and then bring that to a GitHub issue. We don't use the new GitHub discussions feature as I think that would divide the audience.

Hope that helps

**Comment by mattthhdp** [comment]
That make perfect sense, what i would like to have is, the ability to share 1 "docker-folder" with all services under it because some services (traefik, deluge ...) have some config that you need to modify. And with the way it is currently i have to make 1 share per service. It's ok but would be way more easy to copy the docker-folder to make a backup of everything underneath it.
thanks for the answer !

**Comment by FroggyFlox** [comment]
Hi @mattthhdp,
Thanks for the clarification!
You might be interested to know that we have seen requests to implement something that would allow what you are describing; see for instance:
- https://github.com/rockstor/rockstor-core/issues/2258
- #95 

Thanks a lot for bringing this up, then, as that further demonstrates the interest from our users for this feature! Rockstor's a community-driven project so the more interest by users, the more likely it will be prioritized for implementation.

Let me know if I misunderstood what you were seeking, and if the two issues to which I have linked would not fit what you described.

**Comment by FroggyFlox** [comment]
As detailed above, we have an issue that would address this in our rockstor-core repository, which is where the work would need to be done. I'm thus closing this issue here.
