### ISSUE TITLE
Scrutiny Rockon not functional currently

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockon-registry#329]
Based on Rockstor forum member ITStaff's post (https://forum.rockstor.com/t/disk-unusable-as-pool-member/8403/17), it appears that the Scrutiny Rockon is not working currently.
After checking my install I am experiencing issues as well, the container is running, however it is not functional. After a short investigation I found that this issue has been opened:
https://github.com/linuxserver/docker-scrutiny/issues/22

they are in the process of discussing on how to proceed as scrutiny now needs and InfluxDB instance, which is not (yet) part of the linuxserver.io image.

I propose, that we wait for a little bit until Linuxserver makes a decision on how to proceed (requiring a separate container for the database portion, or incorporating it), before taking any action.

Alternative is to force an older version of linuxserver's image until further notice that does not have that prerequisite (was pointed out in the issue reported to lsio).

**Comment by AnalogJ** [comment]
If anyone wants the new functionality provided by the v0.4.x releases (without waiting), they can migrate to the official Scrutiny docker image: ghcr.io/analogj/scrutiny:master-omnibus - where everything works out of the box.

Here's a quick migration guide: https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_INFLUXDB.md#upgrading-from-v03x-to-v04x

**Comment by FroggyFlox** [comment]
@AnalogJ , thanks a lot for bringing your official image to our attention; this seems to be exactly what we are ideally looking for!

@Hooverdan96, @phillxnet , at first glance, I think @AnalogJ's official image is exactly what we should use:
- official image with very active development and support
- is both `amd64` and `arm64` compatible
- the `omnibus` image is an all-in-one image

I would thus vote to switch to using that image instead of the LSIO one. Of note, the initial choice of the LSIO image over the official image was directed (based on https://github.com/rockstor/rockon-registry/pull/261) by the multi-architecture support and all-in-one nature of the LSIO image. Both of these points are no longer exclusive advantages of the LSIO image anymore, so the official image now seems preferred to me. What do you think?

**Comment by phillxnet** [comment]
@FroggyFlox Agreed on all accounts.
@AnalogJ Hello there, and thanks for the pointer/image/project/work here; as always: much appreciated.

**Comment by AnalogJ** [comment]
No problem! Rockstor seems like an interesting project!

**Comment by phillxnet** [comment]
@Hooverdan96 @FroggyFlox @AnalogJ 
I've popped in a pr for the scrutiny image move to official. I've included some notes on stuff I was unsure of and I'd appreciated some feedback / pr review to check my efforts as this repo is normally more the domain of @FroggyFlox and @Hooverdan96. But I like to chip in occasionally ;). Pr contains all Rock-on related Web-UI rendering in picture form and all urls look to be as intended and working. Keen to keep this one as simple to install as possible. Would also appreciate an arm64 test.
