### ISSUE TITLE
Allow storage definition within Rockon install UI

### ISSUE THREAD

**Issue by seffyroff** [rockstor/rockon-registry#95]
Please allow me to define shares at point of deployment during the install UI - the ability to specify a path relative to an existing share (eg /rockonshare/config/plex/) would make the deployment flow way less clunky.

**Comment by FroggyFlox** [comment]
Hi @20design, thanks for your feedback on this issue, Personally, I didn't notice it until now.

Would you and @seffyroff be willing to describe in a little bit more details (maybe with an example?) what you would like to see?
I myself thought about allowing the creation of share(s) from within the Rock-On install wizard (so that one does not have to exist the install wizard, create the share and then start the Rock-On install again), but I'm not sure that corresponds to what is described in this issue.

On a side note, I would maybe recommend to move this discussion to the `rockstor/rockstor-core` repo (https://github.com/rockstor/rockstor-core) and it seems more appropriate there.

**Comment by FroggyFlox** [comment]
That is very close to the top of my list (if not at the very top) of what to address next once I'm done with my current work. 
I haven't thought about details yet, but I like your idea. We may even not have to retrofit all Rock-ons definitions and "simply" use a combination of Rock-on/container name and volume name to automatically create a "sensible" default name for a share. But again, letting the user enter a name would remain much better... Worth having a dedicated issue on `rockstor-core` to discuss this.

**Comment by phillxnet** [comment]
As per @FroggyFlox comment:

> Worth having a dedicated issue on `rockstor-core` to discuss this.

I'll close this in light of it being in the wrong repository anyway. And if there is further interest do please continue this discussion in our https://github.com/rockstor/rockstor-core repo under a new issue as that is where our Rock-ons management code is located. Here, in this repo, we only have Rock-on definitions. A link to this now closed issue in the new issue (if there is interest) would be great as we then have some context and a reference to what has been discussed here to date. Although a summary would be a good starting text in the new issue of course.
